// This file is automatically generated. Do not edit it directly.
//
// Exception (docs/execplans/p2-02-mock-auth-mode.md): the export below is
// gated on `import.meta.env.VITE_MOCK_AUTH`, a build-time flag Vite inlines
// as a literal. When unset (every real build — Lovable's production publish
// never sets it), the condition folds to `false` and the mock branch,
// including the `createMockClient` import, is dead code eligible for
// Rollup's tree-shaking — proved in that plan's Evidence by grepping a
// production `npm run build` for the mock module's sentinel string.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createMockClient } from '@/mocks/mockClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// The mock client structurally covers only the query shapes the four data
// hooks + AuthContext actually emit (see src/mocks/mockClient.ts), not the
// full Database-aware SupabaseClient surface — hence the cast, so callers
// keep the real client's richer typing without a second, narrower type
// propagating through every hook.
export const supabase = (
  import.meta.env.VITE_MOCK_AUTH === 'true'
    ? createMockClient()
    : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      })
) as unknown as SupabaseClient<Database>;